# version: "3.7"

services:
  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./app
      dockerfile: Dockerfile_redis
    command: >
      redis-server redis.conf
    expose:
      - 6380
    ports:
      - 6380:6380
    networks:
      - arealite

  api:
    container_name: api
    hostname: api
    build:
      context: ./app
      dockerfile: Dockerfile_api
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5555
    depends_on:
      - redis
    ports:
      - 5555:5555
    networks:
      - arealite

  flower:
    container_name: flower
    hostname: flower
    image: localhost/flower
    build:
      context: ./app
      dockerfile: Dockerfile_flower
    env_file:
      - .env
    command: >
        celery
          flower
          --broker=$${BROKER_URL}
          --certfile=/app/client.crt
          --keyfile=/app/client.key
          --ca_certs=/app/ca.crt
    ports:
      - 5556:6666
    networks:
      - arealite


# # WORKERS HERE

  celery:
    hostname: add
    image: localhost/celery
    build:
      context: ./app
      dockerfile: Dockerfile_celery
    env_file:
      - .env
    environment:
      # - CELERY_BROKER=rediss://host.docker.internal:6380/0?ssl_cert_reqs=required
      # - CELERY_BACKEND=rediss://host.docker.internal:6380/0?ssl_cert_reqs=required
      - CELERY_BROKER=$${BROKER_URL}
      - CELERY_BACKEND=$${BROKER_URL}
    command: celery -A tasks worker -Q add --loglevel=INFO
    networks:
      - remoteServer


networks:
  arealite:
    driver: bridge

  remoteServer:
    driver: bridge

  multiple:
    driver: bridge