# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements_api.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements_api.txt

COPY ./certs/ .

COPY ./api/main.py .

COPY ./tasks/tasks.py .