# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements_flower.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements_flower.txt

COPY ./certs/ .