# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements_celery.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements_celery.txt

COPY api/ .

COPY ./certs/ .

COPY tasks/ ./tasks/

CMD ['celery', '-A', 'celery_app', 'worker', '--loglevel=INFO']